# Generated by Django 2.1.1 on 2019-04-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='v_video',
        ),
    ]
